---
- name: Generate certificate scritp
  template:
    src: makeCert.j2
    dest: /tmp/makeCert.sh
    mode: 600

- name: Generate Certificates
  shell: /tmp/makeCert.sh
  args:
    chdir: /etc/openldap/certs

- name: Change the permissions Server Certificate
  file:
    path: /etc/openldap/certs/servcert.pem
    owner: ldap
    mode: 400

- name: Change the permissions Server Key
  file:
    path: /etc/openldap/certs/servkey.pem
    owner: ldap
    mode: 400

- name: Distribute CA Certificate
  copy:
    src: /etc/pki/CA/cacert.pem
    dest: /etc/openldap/certs/
    owner: ldap
    mode: 400

- name: Remove script
  file:
    path: /tmp/makeCert.sh
    state: absent
