---
- name: Install Open Ldap
  yum:
    name: "{{ item }}"
    state: present 
  with_items:
    - openldap-servers
    - openldap-clients

- name: Restart slapd
  systemd:
    name: slapd
    state: started 
    enabled: yes
