---
- name: Create ldif to make ldap TLS configurations
  template:
    src: enable_tls.j2
    dest: /tmp/enable_tls.ldif

- name: Execute ldapmodify to config TLS
  shell: ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/enable_tls.ldif

- name: Configure ldaps on slapd file service
  lineinfile:
    path: /etc/sysconfig/slapd
    regexp: 'SLAPD_URLS="ldapi:/// ldap:///"'
    line: 'SLAPD_URLS="ldapi:/// ldap:/// ldaps:///"'
  notify:
    - Restart slapd

- name: Remove ldif file
  file:
    path: /tmp/enable_tls.ldif
    state: absent
